### PR TITLE
make DEFAULT_HANDLER an undefined symbol

### LINKED ISSUE #58: default_handler! doesn't work
The `default_handler!` doesn't work in this [example code](https://github.com/japaric/cortex-m-rt/files/1769278/simple.tar.gz). This was tested with rust-1.26.0-nightly-2018-02-27-29f5c699b:

Debug Build:

```
000004de <_ZN11cortex_m_rt15default_handler17h87e495993753afeeE>:
///
/// That exception frame is a snapshot of the program state right before the
/// exception occurred.
#[allow(unused_variables)]
#[cfg(target_arch = "arm")]
extern "C" fn default_handler(ef: &ExceptionFrame) -> ! {
 4de:   b082            sub     sp, #8
 4e0:   4601            mov     r1, r0
 4e2:   9001            str     r0, [sp, #4]
/// cause an exception
#[inline(always)]
pub fn bkpt() {
    #[cfg(target_arch = "arm")]
    unsafe {
        asm!("bkpt"
 4e4:   be00            bkpt    0x0000
    asm::bkpt();
 4e6:   9100            str     r1, [sp, #0]
 4e8:   e7ff            b.n     4ea <_ZN11cortex_m_rt15default_handler17h87e495993753afeeE+0xc>

    loop {}
 4ea:   e7fe            b.n     4ea <_ZN11cortex_m_rt15default_handler17h87e495993753afeeE+0xc>

000004ec <BUS_FAULT>:
    #[export_name = "DEFAULT_HANDLER"]
    #[linkage = "weak"]
    #[naked]
    extern "C" fn trampoline() -> ! {
        unsafe {
            asm!("mrs r0, MSP
 4ec:   f3ef 8008       mrs     r0, MSP
 4f0:   f7ff bff5       b.w     4de <_ZN11cortex_m_rt15default_handler17h87e495993753afeeE>
                 :
                 : "i"(default_handler as extern "C" fn(&ExceptionFrame) -> !)
                 :
                 : "volatile");

            intrinsics::unreachable()
 4f4:   defe            udf     #254    ; 0xfe
```

Release Build:

```
00000598 <_ZN11cortex_m_rt15default_handler17h6304dc68fb71af89E>:
 598:   be00            bkpt    0x0000
 59a:   e7fe            b.n     59a <_ZN11cortex_m_rt15default_handler17h6304dc68fb71af89E+0x2>

0000059c <BUS_FAULT>:
 59c:   f3ef 8008       mrs     r0, MSP
 5a0:   f7ff bffa       b.w     598 <_ZN11cortex_m_rt15default_handler17h6304dc68fb71af89E>
 5a4:   defe            udf     #254    ; 0xfe
```

### PR DESCRIPTION
**Pull request by japaric**
fixes #58

I found out that this fixes #58 while writing the embedonomicon

### CODE REVIEW

**Comment by japaric** [comment]
@crawford could you give this a spin? I tested with the example code you posted in #58 but perhaps you should try this out with some more complex program.

cc @pftbest you may want to include this in msp430-rt

**Comment by pftbest** [comment]
@japaric Sorry, but looks like this fix doesn't work for me. Are you sure it fixed the issue on your side? I still see that EXCEPTIONS array is wrong.

**Comment by crawford** [comment]
@japaric Gah! I didn't see your note since GitHub doesn't always send me email alerts... I tried this out on my application (rustc 1.27.0-nightly-7360d6dd6 with LLD) and it seems to work. It looks like @pftbest's patch might be more complete though.

**Comment by pftbest** [comment]
lld may not have this issue, it is probably GNU ld specific.

**Comment by crawford** [comment]
@pftbest Uh oh. I'm not seeing the original issue anymore (even with GNU ld).

**Comment by crawford** [comment]
@pftbest I'm seeing the same behavior as you for the example code, but not for my application. My application seems to link properly. I wonder if it is because I don't have a direct dependency on cortex-m-rt.

**Comment by japaric** [comment]
Subsumed by #69

**Pull request closed without merging**
